1. splittida data training, validation ja test dataks
2. tasakaalustada dataset
3. treenida 3 mudelit
	a. random forest
	b. decision tree,
	c. knn neigbors
4. leida tpr, fpr, roc curve
5. leida õige cutoff

#### Read in data

In [8]:
import pandas as pd
%matplotlib inline

df = pd.read_csv("smoke_detection_iot.csv")
print("Shape:", df.shape)
df.head(100)

Shape: (62630, 16)

,Unnamed: 0,UTC,Temperature[C],Humidity[%],TVOC[ppb],eCO2[ppm],Raw H2,Raw Ethanol,Pressure[hPa],PM1.0,PM2.5,NC0.5,NC1.0,NC2.5,CNT,Fire Alarm
0,0,1654733331,20.000,57.36,0,400,12306,18520,939.735,0.00,0.00,0.00,0.000,0.000,0,0
1,1,1654733332,20.015,56.67,0,400,12345,18651,939.744,0.00,0.00,0.00,0.000,0.000,1,0
2,2,1654733333,20.029,55.96,0,400,12374,18764,939.738,0.00,0.00,0.00,0.000,0.000,2,0
3,3,1654733334,20.044,55.28,0,400,12390,18849,939.736,0.00,0.00,0.00,0.000,0.000,3,0
4,4,1654733335,20.059,54.69,0,400,12403,18921,939.744,0.00,0.00,0.00,0.000,0.000,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,1654733426,21.323,53.65,23,419,12528,19619,939.799,0.22,0.69,0.39,0.788,0.449,95,0
96,96,1654733427,21.336,53.96,33,421,12524,19614,939.801,0.20,0.63,0.36,0.718,0.409,96,0
97,97,1654733428,21.349,54.25,21,417,12530,19610,939.795,0.16,0.49,0.28,0.561,0.320,97,0
98,98,1654733429,21.362,54.52,19,418,12529,19626,939.799,0.14,0.44,0.25,0.501,0.286,98,0
99,99,1654733430,21.375,54.74,14,405,12533,19624,939.784,0.12,0.36,0.21,0.414,0.236,99,0

#### Drop unnecessary columns

In [9]:
df = df.drop("CNT", axis = 1)
df = df.drop("UTC", axis = 1)
df.head(100)

,Unnamed: 0,Temperature[C],Humidity[%],TVOC[ppb],eCO2[ppm],Raw H2,Raw Ethanol,Pressure[hPa],PM1.0,PM2.5,NC0.5,NC1.0,NC2.5,Fire Alarm
0,0,20.000,57.36,0,400,12306,18520,939.735,0.00,0.00,0.00,0.000,0.000,0
1,1,20.015,56.67,0,400,12345,18651,939.744,0.00,0.00,0.00,0.000,0.000,0
2,2,20.029,55.96,0,400,12374,18764,939.738,0.00,0.00,0.00,0.000,0.000,0
3,3,20.044,55.28,0,400,12390,18849,939.736,0.00,0.00,0.00,0.000,0.000,0
4,4,20.059,54.69,0,400,12403,18921,939.744,0.00,0.00,0.00,0.000,0.000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,21.323,53.65,23,419,12528,19619,939.799,0.22,0.69,0.39,0.788,0.449,0
96,96,21.336,53.96,33,421,12524,19614,939.801,0.20,0.63,0.36,0.718,0.409,0
97,97,21.349,54.25,21,417,12530,19610,939.795,0.16,0.49,0.28,0.561,0.320,0
98,98,21.362,54.52,19,418,12529,19626,939.799,0.14,0.44,0.25,0.501,0.286,0
99,99,21.375,54.74,14,405,12533,19624,939.784,0.12,0.36,0.21,0.414,0.236,0

#### Split data into train, validation and test

In [10]:
from sklearn.model_selection import train_test_split

ratio_train = 0.7
ratio_val = 0.15
ratio_test = 0.15

x = df.drop("Fire Alarm", axis=1)
y = df["Fire Alarm"]

x_remaining, x_test, y_remaining, y_test = train_test_split(
    x, y, test_size=ratio_test)

ratio_remaining = 1 - ratio_test
ratio_val_adjusted = ratio_val / ratio_remaining


x_train, x_validation, y_train, y_validation = train_test_split(
    x_remaining, y_remaining, test_size=ratio_val_adjusted)

In [11]:
print(x_train.shape)
print(x_val.shape)
print(x_test.shape)

(43840, 13)
(9395, 13)
(9395, 13)

#### Balance training data

In [12]:
from imblearn.over_sampling import ADASYN
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline

over = ADASYN(sampling_strategy=0.9)
under = RandomUnderSampler(sampling_strategy=0.95)

steps = [('o', over), ('u', under)]

pipeline = Pipeline(steps=steps)

x_train_bal, y_train_bal = pipeline.fit_resample(x_train, y_train)

In [16]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, roc_auc_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

parameters = {"n_neighbors":[1, 5, 10],
              "leaf_size": [10, 20, 30]}
knn = KNeighborsClassifier()
clf = GridSearchCV(knn, parameters)
clf.fit(x_train_bal, y_train_bal)
y_pred = clf.predict(x_validation)
confusion_matrix_result = confusion_matrix(y_validation.values, y_pred, labels=[1,0])  # Label=[1,0], otherwise predicted and actual axes are swapped
auc = roc_auc_score(y_validation, clf.predict_proba(x_validation)[:,1])
print("Confusion matrix:\n%s\n" % confusion_matrix_result)
print("auc:%s\n" % auc)

clf.best_params_

Confusion matrix:
[[6763    0]
 [   0 2632]]

auc:1.0

{'leaf_size': 10, 'n_neighbors': 1}

#### Random forest classifier

In [17]:
from sklearn.ensemble import RandomForestClassifier

parameters = {"n_estimators":[200],
              "random_state":[6],
              "max_depth": [None, 1, 2]}
rf = RandomForestClassifier()
clf = GridSearchCV(rf, parameters)
clf.fit(x_train_bal, y_train_bal)
y_pred = clf.predict(x_validation)
confusion_matrix_result = confusion_matrix(y_validation.values, y_pred, labels=[1,0])  # Label=[1,0], otherwise predicted and actual axes are swapped
auc = roc_auc_score(y_validation, clf.predict_proba(x_validation)[:,1])
print("Confusion matrix:\n%s\n" % confusion_matrix_result)
print("auc:%s\n" % auc)

clf.best_params_

Confusion matrix:
[[6763    0]
 [   1 2631]]

auc:1.0

{'max_depth': None, 'n_estimators': 200, 'random_state': 6}

In [18]:
from sklearn.tree import DecisionTreeClassifier

parameters = {"criterion": ["gini", "entropy", "log_loss"],
              "max_depth": [None, 1, 2, 3],
             "random_state":[0, 2, 4, 6, 100],
             "min_samples_split":[2, 5 ,10, 15, 20]}
dtc = DecisionTreeClassifier()

clf = GridSearchCV(dtc, parameters)
clf.fit(x_train_bal, y_train_bal)
y_pred = clf.predict(x_validation)
confusion_matrix_result = confusion_matrix(y_validation.values, y_pred, labels=[1,0])  # Label=[1,0], otherwise predicted and actual axes are swapped
auc = roc_auc_score(y_validation, clf.predict_proba(x_validation)[:,1])
print("Confusion matrix:\n%s\n" % confusion_matrix_result)
print("auc:%s\n" % auc)

clf.best_params_

Confusion matrix:
[[6763    0]
 [   2 2630]]

auc:0.9996200607902735

{'criterion': 'entropy',
 'max_depth': None,
 'min_samples_split': 2,
 'random_state': 4}